# Generated by Django 5.2.3 on 2025-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/', verbose_name='Product Image'),
            preserve_default=False,
        ),
    ]
